mex -DWIN32...
    -I"C:\OpenHaptics\Developer\3.5.0\include"...
    -I"C:\OpenHaptics\Developer\3.5.0\utilities\include"...
    -I"C:\OpenHaptics\Developer\3.5.0\QuickHaptics\header"...
    -L"C:\OpenHaptics\Developer\3.5.0\lib\x64\Release" -lhd -lhl...
    "-LC:\\OpenHaptics\\Developer\\3.5.0\\lib\\x64\\Release"...
    "-lhd" "-lhl"...
    "-LC:\\OpenHaptics\\Developer\\3.5.0\\utilities\\lib\\x64\\Release"...
    "-lhdu" "-lhlu"...   
    "TouchXcontroller_mex.cpp"
